#!/bin/sh

export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0'`;
MYIP2="s/xxxxxxxxx/$MYIP/g";
cd
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
apt-get update;apt-get -y install wget curl;
ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart
cd /var
touch swap.img
chmod 600 swap.img
dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
mkswap /var/swap.img
swapon /var/swap.img
free
echo "/var/swap.img    none    swap    sw    0    0" >> /etc/fstab
sysctl -w vm.swappiness=30
wget -O /etc/apt/sources.list "https://raw.github.com/micky24/debian7os/master/sources.list.debian7"
wget "http://www.dotdeb.org/dotdeb.gpg"
wget "http://www.webmin.com/jcameron-key.asc"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg
cat jcameron-key.asc | apt-key add -;rm jcameron-key.asc

apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove bind9*;
apt-get -y --purge remove exim*;

apt-get update; apt-get -y upgrade;
apt-get -y install bmon iftop htop nmap axel nano iptables traceroute sysv-rc-conf dnsutils bc nethogs vnstat less screen psmisc apt-file whois ptunnel ngrep mtr git zsh unzip unrar rsyslog debsums rkhunter openvpn
apt-get -y install build-essential
service exim4 stop
sysv-rc-conf exim4 off
apt-file update
vnstat -u -i eth0
service vnstat restart
cd
wget 'https://raw.github.com/micky24/debian7os/master/screeftech-dev'
mv screeftech-dev /usr/bin/screenfetch
chmod +x /usr/bin/screenfetch
echo "clear" >> .profile
echo "screenfetch" >> .profile
cd
wget -O /etc/openvpn/ca.crt "https://raw.github.com/micky24/debian7os/master/ca.crt"
wget -O /etc/openvpn/dh1024.pem "https://raw.github.com/micky24/debian7os/master/dh1024.pem"
wget -O /etc/openvpn/server.crt "https://raw.github.com/micky24/debian7os/master/server.crt"
wget -O /etc/openvpn/server.key "https://raw.github.com/micky24/debian7os/master/server.key"
cd /etc/openvpn/
wget -O /etc/openvpn/1194.conf "https://raw.github.com/micky24/debian7os/master/1194.conf"
service openvpn restart
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
wget -O /etc/iptables.up.rules "https://raw.github.com/micky24/debian7os/master/iptables.up.rules.kvm"
sed -i '$ i\iptables-restore < /etc/iptables.up.rules' /etc/rc.local
sed -i $MYIP2 /etc/iptables.up.rules;
iptables-restore < /etc/iptables.up.rules
wget -O /usr/bin/badvpn-udpgw "https://raw.github.com/micky24/debian7os/master/badvpn-udpgw"
if [ "$OS" == "x86_64" ]; then
  wget -O /usr/bin/badvpn-udpgw "https://raw.github.com/micky24/debian7os/master/badvpn-udpgw64"
fi
sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
chmod +x /usr/bin/badvpn-udpgw
screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300
wget -O /etc/snmp/snmpd.conf "https://raw.github.com/micky24/debian7os/master/snmpd.conf"
wget -O /root/mrtg-mem.sh "https://raw.github.com/micky24/debian7os/master/mrtg-mem.sh"
chmod +x /root/mrtg-mem.sh
sed -i '/Port 22/a Port 143' /etc/ssh/sshd_config
sed -i 's/#Banner/Banner/g' /etc/ssh/sshd_config
service ssh restart
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS=""/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
service ssh restart
service dropbear restart
apt-get -y install fail2ban;service fail2ban restart
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.github.com/micky24/debian7os/master/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart
cd
wget http://jaist.dl.sourceforge.net/project/webadmin/webmin/1.791/webmin_1.791_all.deb
dpkg -i --force-all webmin_1.791_all.deb;
apt-get -y -f install;
rm /root/webmin*
service webmin restart
service vnstat restart
cd
apt-get -y --force-yes -f install libxml-parser-perl
wget -O speedtest_cli.py "https://raw.github.com/sivel/speedtest-cli/master/speedtest_cli.py"
wget -O bench-network.sh "https://raw.github.com/micky24/debian7os/master/bench-network.sh"
wget -O ps_mem.py "https://raw.github.com/pixelb/ps_mem/master/ps_mem.py"
wget -O dropmon "https://raw.github.com/micky24/debian7os/master/dropmon.sh"
wget -O userlogin.sh "https://raw.github.com/micky24/debian7os/master/userlogin.sh"
wget -O userexpired.sh "https://raw.github.com/micky24/debian7os/master/userexpired.sh"
wget -O expire.sh "https://raw.github.com/micky24/debian7os/master/expire.sh"
wget -O /etc/issue.net "https://raw.github.com/micky24/debian7os/master/banner"
echo "0 */24 * * * root /root/userexpired.sh" > /etc/cron.d/userexpired
echo "@reboot root /root/userlimit.sh" > /etc/cron.d/userlimit
echo "0 */6 * * * root /sbin/reboot" > /etc/cron.d/reboot
chmod +x bench-network.sh
chmod +x speedtest_cli.py
chmod +x ps_mem.py
chmod +x userlogin.sh
chmod +x userexpired.sh
chmod +x dropmon
chmod +x expire.sh
service cron restart
service vnstat restart
service ssh restart
service dropbear restart
service fail2ban restart
service squid3 restart
service webmin restart
rm -rf ~/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile
echo "INSTALLASI SELESAI!!!"
echo "SILAHKAN REEBOT VPS ANDA"
cd
rm -f /root/install
